"""Investigation domain: explicit context, the closed refinement set,
carryover laws, turn taxonomy, and session/investigation records."""

from revi_investigation.domain.context import (
    AnalysisSpec,
    ContextPin,
    InvestigationContext,
    PackVersionRef,
    empty_context,
)
from revi_investigation.domain.records import (
    Finding,
    Investigation,
    InvestigationStatus,
    RefinementEdge,
    Session,
    SessionLineage,
)
from revi_investigation.domain.refinements import (
    KERNEL_ONLY_OPERATORS,
    PLAN_ONLY_OPERATORS,
    AddFilter,
    CohortResolver,
    DrillInto,
    Expand,
    Explain,
    Pivot,
    RankBy,
    Refinement,
    RemoveFilter,
    ResetContext,
    SetComparison,
    SetDimensions,
    SetGrain,
    SetWindow,
    apply_refinement,
    apply_refinements,
    detect_conflict,
)
from revi_investigation.domain.turns import (
    ZERO_PROBE_TURN_CLASSES,
    ClarificationRequest,
    TurnClass,
    TurnClassification,
)

__all__ = [
    "KERNEL_ONLY_OPERATORS",
    "PLAN_ONLY_OPERATORS",
    "ZERO_PROBE_TURN_CLASSES",
    "AddFilter",
    "AnalysisSpec",
    "ClarificationRequest",
    "CohortResolver",
    "ContextPin",
    "DrillInto",
    "Expand",
    "Explain",
    "Finding",
    "Investigation",
    "InvestigationContext",
    "InvestigationStatus",
    "PackVersionRef",
    "Pivot",
    "RankBy",
    "Refinement",
    "RefinementEdge",
    "RemoveFilter",
    "ResetContext",
    "Session",
    "SessionLineage",
    "SetComparison",
    "SetDimensions",
    "SetGrain",
    "SetWindow",
    "TurnClass",
    "TurnClassification",
    "apply_refinement",
    "apply_refinements",
    "detect_conflict",
    "empty_context",
]
