"""Revi shared kernel.

Scope objects, the filter algebra, the evidence-probe union, evidence
frames, watermarks, evidence grades, cohorts, the repository port, exact
money, and the stable error codes. Everything here is frozen, typed, and
free of vendor or framework imports (enforced by import-linter).
"""

from revi_kernel.capabilities import AnalyticalRepository, RepositoryCapabilities
from revi_kernel.cohort import CohortDefinition, CohortMaterialization, CohortRef
from revi_kernel.errors import ERROR_TYPES, ErrorCode, ReviError
from revi_kernel.filters import (
    EMPTY_SCOPE,
    And,
    FilterExpr,
    InCohort,
    Not,
    Or,
    Predicate,
    PredicateOp,
    Scalar,
    and_merge,
    dimensions_used,
    is_empty,
    iter_cohorts,
    iter_predicates,
)
from revi_kernel.frame import (
    EvidenceFrame,
    FrameColumn,
    FrameRow,
    FrameSchema,
    ProbeProvenance,
    ProvenanceRef,
    TransformProvenance,
)
from revi_kernel.grades import EvidenceGrade, min_grade
from revi_kernel.money import cents_to_dollars, dollars_to_cents, format_cents
from revi_kernel.probes import (
    AggregationProbe,
    EvidenceProbe,
    MeasurePredicate,
    Ordering,
    RowEvidenceProbe,
    SampleMethod,
    SamplePolicy,
    SnapshotProbe,
    canonical_json,
    probe_hash,
)
from revi_kernel.refs import (
    DISCHARGE,
    POST,
    REMIT,
    SERVICE,
    STANDARD_DATE_BASES,
    SUBMISSION,
    DateBasisRef,
    DimensionRef,
    EntityGrain,
    FieldRef,
    Grain,
    MetricRef,
    ReferentId,
    ReferentKind,
    TimeBucket,
)
from revi_kernel.scope import (
    BUSINESS_CALENDAR,
    DEFAULT_CALENDAR,
    AbsoluteRange,
    CalendarPolicy,
    CalendarRef,
    Comparison,
    ComparisonKind,
    RangeMode,
    RelativeRange,
    TimeUnit,
    TimeWindow,
    derive_comparison,
    resolve_relative,
    resolve_window,
    shift_months,
    shift_years,
)
from revi_kernel.watermark import DataWatermark, WatermarkEpoch

__all__ = [
    "BUSINESS_CALENDAR",
    "DEFAULT_CALENDAR",
    "DISCHARGE",
    "EMPTY_SCOPE",
    "ERROR_TYPES",
    "POST",
    "REMIT",
    "SERVICE",
    "STANDARD_DATE_BASES",
    "SUBMISSION",
    "AbsoluteRange",
    "AggregationProbe",
    "AnalyticalRepository",
    "And",
    "CalendarPolicy",
    "CalendarRef",
    "CohortDefinition",
    "CohortMaterialization",
    "CohortRef",
    "Comparison",
    "ComparisonKind",
    "DataWatermark",
    "DateBasisRef",
    "DimensionRef",
    "EntityGrain",
    "ErrorCode",
    "EvidenceFrame",
    "EvidenceGrade",
    "EvidenceProbe",
    "FieldRef",
    "FilterExpr",
    "FrameColumn",
    "FrameRow",
    "FrameSchema",
    "Grain",
    "InCohort",
    "MeasurePredicate",
    "MetricRef",
    "Not",
    "Or",
    "Ordering",
    "Predicate",
    "PredicateOp",
    "ProbeProvenance",
    "ProvenanceRef",
    "RangeMode",
    "ReferentId",
    "ReferentKind",
    "RelativeRange",
    "RepositoryCapabilities",
    "ReviError",
    "RowEvidenceProbe",
    "SampleMethod",
    "SamplePolicy",
    "Scalar",
    "SnapshotProbe",
    "TimeBucket",
    "TimeUnit",
    "TimeWindow",
    "TransformProvenance",
    "WatermarkEpoch",
    "and_merge",
    "canonical_json",
    "cents_to_dollars",
    "derive_comparison",
    "dimensions_used",
    "dollars_to_cents",
    "format_cents",
    "is_empty",
    "iter_cohorts",
    "iter_predicates",
    "min_grade",
    "probe_hash",
    "resolve_relative",
    "resolve_window",
    "shift_months",
    "shift_years",
]
