"""Presentation: chart specs, canonical context headers, narrative
grounding validation. Pure functions over kernel frames and contract DTOs
— this package never imports capability implementations."""

from revi_investigation_contracts.header import build_header_payload
from revi_presentation.charts import (
    DEFAULT_WINDOW_KEY,
    ChartSuggestion,
    ChartWindow,
    RecipeSpec,
    build_chart_spec,
    build_chart_specs,
    period_label,
    provisional_bucket,
    window_from_facts,
)
from revi_presentation.narrative import (
    DOUBLED_SPAN_CHARS,
    DUPLICATE_SENTENCE_REASON,
    LEAD_DISCLOSURE_CODES,
    MANDATORY_DISCLOSURE_CODES,
    NARRATIVE_TEMPLATE,
    NARRATIVE_TEMPLATE_ANALYST,
    NARRATIVE_TEMPLATE_ID,
    NARRATIVE_TEMPLATE_VERSION,
    NARRATIVE_TEMPLATES,
    OPERATOR_ONLY_DISCLOSURE_CODES,
    REDACTION_NOTE,
    REDACTION_WARNING_PREFIX,
    apply_metric_display,
    build_narrative_facts,
    build_narrative_prompt,
    compose_narrative,
    dedupe_sentences,
    doubled_span,
    empty_narrative,
    ends_on_abbreviation,
    mandatory_disclosures,
    operator_only_disclosures,
    reconciliation_disclosure,
    recovered_code,
    split_sentences,
    template_hash,
    validate_narrative,
)

__all__ = [
    "DEFAULT_WINDOW_KEY",
    "DOUBLED_SPAN_CHARS",
    "DUPLICATE_SENTENCE_REASON",
    "LEAD_DISCLOSURE_CODES",
    "MANDATORY_DISCLOSURE_CODES",
    "NARRATIVE_TEMPLATE",
    "NARRATIVE_TEMPLATES",
    "NARRATIVE_TEMPLATE_ANALYST",
    "NARRATIVE_TEMPLATE_ID",
    "NARRATIVE_TEMPLATE_VERSION",
    "OPERATOR_ONLY_DISCLOSURE_CODES",
    "REDACTION_NOTE",
    "REDACTION_WARNING_PREFIX",
    "ChartSuggestion",
    "ChartWindow",
    "RecipeSpec",
    "apply_metric_display",
    "build_chart_spec",
    "build_chart_specs",
    "build_header_payload",
    "build_narrative_facts",
    "build_narrative_prompt",
    "compose_narrative",
    "dedupe_sentences",
    "doubled_span",
    "empty_narrative",
    "ends_on_abbreviation",
    "mandatory_disclosures",
    "operator_only_disclosures",
    "period_label",
    "provisional_bucket",
    "reconciliation_disclosure",
    "recovered_code",
    "split_sentences",
    "template_hash",
    "validate_narrative",
    "window_from_facts",
]
