/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/capabilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Capabilities */
        get: operations["get_capabilities_v1_capabilities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/investigations/{investigation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Investigation */
        get: operations["get_investigation_v1_investigations__investigation_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/portfolio/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Portfolio */
        get: operations["get_portfolio_v1_portfolio_latest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Open Session */
        post: operations["open_session_v1_sessions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sessions/{session_id}/lineage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Lineage */
        get: operations["get_lineage_v1_sessions__session_id__lineage_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sessions/{session_id}/turns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit Turn */
        post: operations["submit_turn_v1_sessions__session_id__turns_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AbsoluteWindowModel */
        AbsoluteWindowModel: {
            /**
             * End
             * Format: date
             */
            end: string;
            /**
             * Start
             * Format: date
             */
            start: string;
        };
        /** AddFilterModel */
        AddFilterModel: {
            /** Dimension */
            dimension: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            op: "add_filter";
            /**
             * Predicate Op
             * @enum {string}
             */
            predicate_op: "eq" | "neq" | "in" | "not_in" | "range" | "is_null" | "contains";
            /** Values */
            values?: (string | number | boolean | null)[];
        };
        /**
         * AnomalyCard
         * @description One detected anomaly, ranked by the governed priority formula.
         *
         *     The decomposed components (impact, age, recoverable estimate,
         *     actionability rationale) travel with the score — no black-box
         *     ordering — and ``drill_filters`` + ``drill_window`` are the typed
         *     handle the UI uses to start an ordinary investigation turn.
         */
        AnomalyCard: {
            /**
             * Actionability Label
             * @default
             */
            actionability_label: string;
            /**
             * Actionability Rationale
             * @default
             */
            actionability_rationale: string;
            /**
             * Age Days
             * @default 0
             */
            age_days: number;
            /** Anomaly Id */
            anomaly_id: string;
            /** Category */
            category: string;
            /**
             * Compliance Floor Applied
             * @default false
             */
            compliance_floor_applied: boolean;
            /** Confidence */
            confidence: string;
            /** Description */
            description: string;
            /**
             * Detected At
             * Format: date-time
             */
            detected_at: string;
            /** Dimensions */
            dimensions?: components["schemas"]["AnomalyDimension"][];
            /** Drill Filters */
            drill_filters?: components["schemas"]["AddFilterModel"][];
            drill_window?: components["schemas"]["AbsoluteWindowModel"] | null;
            /**
             * Impact Cents
             * @default 0
             */
            impact_cents: number;
            /** Metric Id */
            metric_id: string;
            /**
             * Priority Score
             * @default 0
             */
            priority_score: number;
            /**
             * Recoverable Cents Estimate
             * @default 0
             */
            recoverable_cents_estimate: number;
            /** Severity */
            severity: string;
            /** Status */
            status: string;
            /** Title */
            title: string;
            /**
             * Window End
             * Format: date
             */
            window_end: string;
            /**
             * Window Start
             * Format: date
             */
            window_start: string;
        };
        /** AnomalyDimension */
        AnomalyDimension: {
            /** Dimension */
            dimension: string;
            /** Value */
            value: string;
        };
        /** CapabilitiesResponse */
        CapabilitiesResponse: {
            /**
             * Llm
             * @default mock
             */
            llm: string;
            /**
             * Newest Watermark Id
             * @default
             */
            newest_watermark_id: string;
            /**
             * Pack Id
             * @default
             */
            pack_id: string;
            /**
             * Pack Snapshot Id
             * @default
             */
            pack_snapshot_id: string;
            /**
             * Pack Version
             * @default
             */
            pack_version: string;
            /** Repository */
            repository?: {
                [key: string]: unknown;
            };
        };
        /** DrillIntoModel */
        DrillIntoModel: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            op: "drill_into";
            /** Target */
            target: string;
        };
        /** ExpandModel */
        ExpandModel: {
            /** Limit */
            limit: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            op: "expand";
        };
        /** ExplainModel */
        ExplainModel: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            op: "explain";
            /** Target */
            target: string;
        };
        /** FindingPayload */
        FindingPayload: {
            /**
             * Confidence
             * @default high
             */
            confidence: string;
            /**
             * Grade
             * @default direct
             */
            grade: string;
            /** Impact Cents */
            impact_cents?: number | null;
            /** Metric Ids */
            metric_ids?: string[];
            /** Referent */
            referent: string;
            /** Statement */
            statement: string;
            /** Suggested Refinements */
            suggested_refinements?: string[];
            /** Title */
            title: string;
            /** Values */
            values?: components["schemas"]["FindingValue"][];
        };
        /** FindingValue */
        FindingValue: {
            /** Name */
            name: string;
            /** Value */
            value?: string | number | boolean | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** InvestigationResponse */
        InvestigationResponse: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Findings */
            findings?: components["schemas"]["FindingPayload"][];
            /** Investigation Id */
            investigation_id: string;
            /** Parent Id */
            parent_id?: string | null;
            /** Plan Hash */
            plan_hash?: string | null;
            /** Question */
            question?: string | null;
            /** Session Id */
            session_id: string;
            /** Status */
            status: string;
            /** Turn Class */
            turn_class: string;
            /** Turn Id */
            turn_id: string;
            /** Warnings */
            warnings?: string[];
        };
        /** LineageEdgePayload */
        LineageEdgePayload: {
            /** Child Id */
            child_id: string;
            /** Operators */
            operators?: {
                [key: string]: unknown;
            }[];
            /** Parent Id */
            parent_id: string;
            /** Turn Id */
            turn_id: string;
        };
        /** OpenSessionRequest */
        OpenSessionRequest: {
            /** Session Id */
            session_id?: string | null;
            /** Tenant */
            tenant: string;
        };
        /** PivotModel */
        PivotModel: {
            /** Measures */
            measures: string[];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            op: "pivot";
        };
        /**
         * PortfolioResponse
         * @description Detected anomalies at the pinned watermark, governed-priority ranked.
         */
        PortfolioResponse: {
            /**
             * Formula Version
             * @default
             */
            formula_version: string;
            /** Items */
            items?: components["schemas"]["AnomalyCard"][];
            /**
             * Status
             * @default empty
             * @enum {string}
             */
            status: "ok" | "empty";
            /** Warnings */
            warnings?: string[];
            /**
             * Watermark Id
             * @default
             */
            watermark_id: string;
            /** Weights */
            weights?: {
                [key: string]: number;
            };
        };
        /** RankByModel */
        RankByModel: {
            /** By */
            by: string;
            /**
             * Descending
             * @default true
             */
            descending: boolean;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            op: "rank_by";
        };
        /** RemoveFilterModel */
        RemoveFilterModel: {
            /** Dimension */
            dimension: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            op: "remove_filter";
        };
        /** ResetContextModel */
        ResetContextModel: {
            /**
             * Keep Pins
             * @default true
             */
            keep_pins: boolean;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            op: "reset_context";
        };
        /** SessionLineageResponse */
        SessionLineageResponse: {
            /** Edges */
            edges?: components["schemas"]["LineageEdgePayload"][];
            /** Investigations */
            investigations?: components["schemas"]["InvestigationResponse"][];
            session: components["schemas"]["SessionResponse"];
        };
        /** SessionResponse */
        SessionResponse: {
            /** Epoch */
            epoch: number;
            /**
             * Newest Data Date
             * Format: date
             */
            newest_data_date: string;
            /** Pack Id */
            pack_id: string;
            /** Pack Version */
            pack_version: string;
            /** Session Id */
            session_id: string;
            /** Tenant */
            tenant: string;
            /** Watermark Id */
            watermark_id: string;
            /**
             * Watermark Loaded At
             * Format: date-time
             */
            watermark_loaded_at: string;
        };
        /** SetComparisonModel */
        SetComparisonModel: {
            custom?: components["schemas"]["AbsoluteWindowModel"] | null;
            /** Kind */
            kind?: ("prior_period" | "prior_year") | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            op: "set_comparison";
        };
        /** SetDimensionsModel */
        SetDimensionsModel: {
            /** Dimensions */
            dimensions: string[];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            op: "set_dimensions";
        };
        /** SetGrainModel */
        SetGrainModel: {
            /**
             * Entity
             * @enum {string}
             */
            entity: "claim" | "line" | "encounter" | "transaction" | "remit" | "denial";
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            op: "set_grain";
            /** Time Bucket */
            time_bucket?: ("day" | "week" | "month") | null;
        };
        /** SetWindowModel */
        SetWindowModel: {
            /** Basis */
            basis?: string | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            op: "set_window";
            /** Window */
            window: components["schemas"]["WindowSpecModel"] | components["schemas"]["AbsoluteWindowModel"];
        };
        /**
         * TurnRequest
         * @description One turn: an utterance OR typed refinement operators (§12).
         */
        TurnRequest: {
            /** Clarification Response */
            clarification_response?: string | null;
            /** Correlation Id */
            correlation_id?: string | null;
            /** Idempotency Key */
            idempotency_key?: string | null;
            /**
             * Re Anchor
             * @default false
             */
            re_anchor: boolean;
            /** Refinements */
            refinements?: (components["schemas"]["SetDimensionsModel"] | components["schemas"]["AddFilterModel"] | components["schemas"]["RemoveFilterModel"] | components["schemas"]["SetWindowModel"] | components["schemas"]["SetComparisonModel"] | components["schemas"]["SetGrainModel"] | components["schemas"]["DrillIntoModel"] | components["schemas"]["PivotModel"] | components["schemas"]["ExplainModel"] | components["schemas"]["RankByModel"] | components["schemas"]["ExpandModel"] | components["schemas"]["ResetContextModel"])[] | null;
            /** Utterance */
            utterance?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * WindowSpecModel
         * @description A relative window; ``quantity`` is a decimal string ("1", "3.25").
         */
        WindowSpecModel: {
            /**
             * Mode
             * @enum {string}
             */
            mode: "trailing" | "full_periods" | "to_date";
            /** Quantity */
            quantity: string;
            /**
             * Unit
             * @enum {string}
             */
            unit: "day" | "week" | "month" | "quarter" | "year";
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_capabilities_v1_capabilities_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CapabilitiesResponse"];
                };
            };
        };
    };
    health_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    get_investigation_v1_investigations__investigation_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                investigation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvestigationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_portfolio_v1_portfolio_latest_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioResponse"];
                };
            };
        };
    };
    open_session_v1_sessions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OpenSessionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_lineage_v1_sessions__session_id__lineage_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionLineageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_turn_v1_sessions__session_id__turns_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TurnRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
