/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/capabilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Capabilities
         * @description Repository capabilities, pinned pack, newest watermark, LLM mode.
         */
        get: operations["get_capabilities_v1_capabilities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness plus the wiring actually in effect (stores, LLM mode).
         */
        get: operations["health_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/investigations/{investigation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Investigation
         * @description Re-fetch a completed turn (reconnect / refresh recovery).
         */
        get: operations["get_investigation_v1_investigations__investigation_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/investigations/{investigation_id}/trace": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Trace
         * @description One turn's decision breakdown: classification and confidence,
         *     the ids interpretation chose, refinement operators, plan hash and
         *     §6.6 outcomes, per-probe rows/timings, per-call model spend and
         *     failure kind, watermark epoch and pack version.
         *
         *     The same projection the `debug` block on a turn response carries —
         *     this route is for the turn nobody thought to debug until after it
         *     answered. Free text is filtered by the outbound-payload guard and
         *     anything withheld is named in `redactions`. `REVI_DEBUG_TRACE=0`
         *     turns the whole surface off (POLICY_DENIED).
         */
        get: operations["get_trace_v1_investigations__investigation_id__trace_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/portfolio/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Portfolio
         * @description Detected anomalies at the pinned watermark, governed-priority
         *     ranked. Cards carry `provenance` rather than an evidence grade.
         */
        get: operations["get_portfolio_v1_portfolio_latest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Sessions
         * @description The caller tenant's sessions, newest activity first.
         *
         *     Every row is derived, never stored: the title is the session's
         *     first question verbatim, and `last_activity` is its newest
         *     investigation. There is no tenant parameter — the token decides
         *     whose sessions these are, so no request can ask for another
         *     tenant's list at all.
         */
        get: operations["list_sessions_v1_sessions_get"];
        put?: never;
        /**
         * Open Session
         * @description Open a session pinned to the newest watermark and active pack.
         *
         *     The tenant comes from the token. A body naming a different one is
         *     refused rather than honored — that field used to be the only thing
         *     deciding which tenant a session belonged to.
         */
        post: operations["open_session_v1_sessions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sessions/{session_id}/lineage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Lineage
         * @description The session's investigation DAG: nodes plus refinement edges.
         */
        get: operations["get_lineage_v1_sessions__session_id__lineage_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sessions/{session_id}/turns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit one turn (utterance OR typed refinement operators)
         * @description **`Accept: text/event-stream`** streams Server-Sent Events;
         *     **`Accept: application/json`** blocks and returns the same
         *     `TurnResponse` body. One route, two transports.
         *
         *     Each SSE frame is `event: <kind>` + `data: <json>` — see the
         *     `TurnStreamEvent` schema. Frame kinds and payloads:
         *
         *     - `stage` — {stage: str} — pipeline progress (classify, plan, validate, execute, calculate, findings, present, narrate).
         *     - `warning` — {code: str, ...} — a stable §12 code plus code-specific detail (e.g. WATERMARK_STALE carries pinned/newest, RECONCILIATION_FAILED carries detail).
         *     - `clarification` — {question: str, reason: str|null} — a successful outcome, never an error.
         *     - `context_header` — ContextHeaderPayload — the effective context of the answer (§7.2); emitted before any finding.
         *     - `finding` — FindingPayload — one certified, referent-addressable result.
         *     - `chart_spec` — ChartSpec — a renderable chart whose row referent ids compile clicks into typed DrillInto refinements.
         *     - `narrative_delta` — {delta: str} — one streamed narrative chunk; provisional until turn_complete.
         *     - `error` — ErrorEnvelope — a failed turn; the stream then ends.
         *     - `turn_complete` — TurnResponse — the FULL authoritative payload. The stream is progress; this last frame is the answer.
         *
         *     The stream is progress; the final `turn_complete` frame carries the
         *     authoritative `TurnResponse`. `CLARIFICATION_REQUIRED` is a 200
         *     outcome, never an error.
         */
        post: operations["submit_turn_v1_sessions__session_id__turns_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AbsoluteWindowModel */
        AbsoluteWindowModel: {
            /**
             * End
             * Format: date
             */
            end: string;
            /**
             * Start
             * Format: date
             */
            start: string;
        };
        /** AddFilterModel */
        AddFilterModel: {
            /** Dimension */
            dimension: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            op: "add_filter";
            /**
             * Predicate Op
             * @enum {string}
             */
            predicate_op: "eq" | "neq" | "in" | "not_in" | "range" | "is_null" | "contains";
            /** Values */
            values?: (string | number | boolean | null)[];
        };
        /**
         * AnomalyCard
         * @description One detected anomaly, ranked by the governed priority formula.
         *
         *     The decomposed components (impact, age, recoverable estimate,
         *     actionability rationale) travel with the score — no black-box
         *     ordering — and ``drill_spec`` is the typed handle the UI posts to
         *     start an ordinary investigation turn.
         *
         *     ``drill_spec`` is a complete :class:`TypedInvestigationSpec`, not a
         *     bag of operators: the card's own metric, its dimensions (both as the
         *     breakdown and, at their detected values, as the scope), and its
         *     observation window. Posting it re-derives the detector's assertion
         *     from the platform's certified semantics and versioned contracts — so
         *     the answer carries a real evidence grade where the card itself only
         *     carries provenance. Earlier milestones shipped ``drill_filters`` +
         *     ``drill_window``, which were sound operators with nowhere to land: a
         *     refinement refines a parent investigation and a card is not one.
         *
         *     **No evidence grade, by construction.** A grade certifies how a number
         *     was *computed by this platform* from certified semantics (design §5.3);
         *     an anomaly card is not that. It is a record read from an external
         *     detection system as-of a watermark, so the platform cannot honestly
         *     stamp DIRECT/DERIVED/PROXY on it. Instead every card declares its
         *     ``provenance`` (``external_detection``), the ``priority_formula_version``
         *     that ordered it, and the ``source_watermark_id`` it was read at — the
         *     three facts a grade would otherwise have implied. Drilling a card starts
         *     an ordinary investigation turn, and *that* answer carries a real grade.
         */
        AnomalyCard: {
            /**
             * Actionability Label
             * @default
             */
            actionability_label: string;
            /**
             * Actionability Rationale
             * @default
             */
            actionability_rationale: string;
            /**
             * Age Days
             * @default 0
             */
            age_days: number;
            /** Anomaly Id */
            anomaly_id: string;
            /** Category */
            category: string;
            /**
             * Compliance Floor Applied
             * @default false
             */
            compliance_floor_applied: boolean;
            /** Confidence */
            confidence: string;
            /** Description */
            description: string;
            /**
             * Detected At
             * Format: date-time
             */
            detected_at: string;
            /** Dimensions */
            dimensions?: components["schemas"]["AnomalyDimension"][];
            /** Drill Repoint Rationale */
            drill_repoint_rationale?: string | null;
            /** Drill Repointed From */
            drill_repointed_from?: string | null;
            drill_spec: components["schemas"]["TypedInvestigationSpec"];
            /** Drill Unavailable Reason */
            drill_unavailable_reason?: string | null;
            /**
             * Drillable
             * @default true
             */
            drillable: boolean;
            /**
             * Impact Cents
             * @default 0
             */
            impact_cents: number;
            /** Metric Id */
            metric_id: string;
            /** Priority Formula Version */
            priority_formula_version: string;
            /**
             * Priority Score
             * @default 0
             */
            priority_score: number;
            /**
             * Provenance
             * @constant
             */
            provenance: "external_detection";
            /**
             * Recoverable Cents Estimate
             * @default 0
             */
            recoverable_cents_estimate: number;
            /** Severity */
            severity: string;
            /** Source Watermark Id */
            source_watermark_id: string;
            /** Status */
            status: string;
            /** Title */
            title: string;
            /**
             * Window End
             * Format: date
             */
            window_end: string;
            /**
             * Window Start
             * Format: date
             */
            window_start: string;
        };
        /** AnomalyDimension */
        AnomalyDimension: {
            /** Dimension */
            dimension: string;
            /** Value */
            value: string;
        };
        /**
         * BenchmarkPayload
         * @description One governed external benchmark range for a metric.
         *
         *     A range, never a point target, and never separable from its context:
         *     ``cohort_label``, ``period``, ``authority``, ``cautions`` and
         *     ``review_status`` are all required on the wire because a figure quoted
         *     without them is a different claim from the one its source made.
         *     ``review_status`` is ``machine_researched`` for every figure shipped so
         *     far — a consumer that renders these as certified truth is asserting
         *     more than the pack does.
         */
        BenchmarkPayload: {
            /** Authority */
            authority: string;
            /** Cautions */
            cautions?: string[];
            /** Cohort Label */
            cohort_label: string;
            /** Id */
            id: string;
            /** Metric Id */
            metric_id: string;
            /** Period */
            period: string;
            /** Review Status */
            review_status: string;
            /** Sources */
            sources?: string[];
            /** Unit */
            unit: string;
            /** Value High */
            value_high: string;
            /** Value Low */
            value_low: string;
        };
        /** CapabilitiesResponse */
        CapabilitiesResponse: {
            /**
             * Llm
             * @default mock
             */
            llm: string;
            /**
             * Newest Watermark Id
             * @default
             */
            newest_watermark_id: string;
            /**
             * Pack Id
             * @default
             */
            pack_id: string;
            /**
             * Pack Snapshot Id
             * @default
             */
            pack_snapshot_id: string;
            /**
             * Pack Version
             * @default
             */
            pack_version: string;
            /** Repository */
            repository?: {
                [key: string]: unknown;
            };
            settings?: components["schemas"]["SettingsBoundsPayload"];
        };
        /** ChartRow */
        ChartRow: {
            /** Referent Id */
            referent_id?: string | null;
            /** Series */
            series?: string | null;
            /** Value */
            value?: string | number | null;
            /** X */
            x: string;
        };
        /**
         * ChartSpec
         * @description A renderable chart; row referent ids make clicks compile to
         *     ``DrillInto`` — no natural language in the gesture loop.
         */
        ChartSpec: {
            /** Annotations */
            annotations?: string[];
            /**
             * Chart Type
             * @enum {string}
             */
            chart_type: "bar" | "grouped_bar" | "stacked_bar" | "line" | "waterfall" | "table" | "range_band";
            /** Frame Id */
            frame_id: string;
            /**
             * Grade
             * @default direct
             */
            grade: string;
            /** Id */
            id: string;
            /** Recipe Id */
            recipe_id?: string | null;
            /** Rows */
            rows?: components["schemas"]["ChartRow"][];
            /** Series */
            series?: string | null;
            /** Title */
            title: string;
            /** Unit */
            unit?: string | null;
            /** Value */
            value: string;
            /** X */
            x: string;
        };
        /**
         * ContextHeaderPayload
         * @description Structured chips plus the canonical one-line display string.
         */
        ContextHeaderPayload: {
            /** Basis */
            basis: string;
            /** Cohort */
            cohort?: string | null;
            /** Cohort Size */
            cohort_size?: number | null;
            /** Comparison End */
            comparison_end?: string | null;
            /** Comparison Kind */
            comparison_kind?: string | null;
            /** Comparison Start */
            comparison_start?: string | null;
            /**
             * Display
             * @default
             */
            display: string;
            /** Filter Chips */
            filter_chips?: components["schemas"]["FilterChip"][];
            /** Filters */
            filters?: string[];
            /**
             * Watermark Id
             * @default
             */
            watermark_id: string;
            /**
             * Window End
             * Format: date
             */
            window_end: string;
            /**
             * Window Start
             * Format: date
             */
            window_start: string;
        };
        /**
         * DebugInterpretation
         * @description What the interpretation stage chose, by id.
         */
        DebugInterpretation: {
            /** Basis */
            basis?: string | null;
            /** Concept Ids */
            concept_ids?: string[];
            /** Dimension Ids */
            dimension_ids?: string[];
            /**
             * Intent Summary
             * @default
             */
            intent_summary: string;
            /** Metric Ids */
            metric_ids?: string[];
            /** Playbook Id */
            playbook_id?: string | null;
            /** Window End */
            window_end?: string | null;
            /** Window Start */
            window_start?: string | null;
        };
        /**
         * DebugLlmCall
         * @description One model call: what was asked, on what, at what price.
         *
         *     ``failure`` is the :class:`LlmFailureKind` value when the call came
         *     back with nothing usable — ``declined`` / ``schema`` / ``off_script``
         *     — because "the model had no mapping for this" and "the answer never
         *     arrived in a readable shape" want opposite recoveries.
         */
        DebugLlmCall: {
            /**
             * Attempts
             * @default 1
             */
            attempts: number;
            /**
             * Cost Usd
             * @default 0
             */
            cost_usd: string;
            /**
             * Duration Ms
             * @default 0
             */
            duration_ms: number;
            /** Failure */
            failure?: string | null;
            /**
             * Input Tokens
             * @default 0
             */
            input_tokens: number;
            /** Model */
            model: string;
            /**
             * Output Tokens
             * @default 0
             */
            output_tokens: number;
            /**
             * Schema Retries
             * @default 0
             */
            schema_retries: number;
            /** Template */
            template: string;
        };
        /**
         * DebugProbe
         * @description One planned probe and what executing it actually produced.
         */
        DebugProbe: {
            /**
             * Cache Hit
             * @default false
             */
            cache_hit: boolean;
            /**
             * Duration Ms
             * @default 0
             */
            duration_ms: number;
            /** Grade */
            grade?: string | null;
            /** Hash */
            hash: string;
            /** Id */
            id: string;
            /**
             * Kind
             * @default
             */
            kind: string;
            /** Limit */
            limit?: number | null;
            /** Metrics */
            metrics?: {
                [key: string]: unknown;
            }[];
            /**
             * Purpose
             * @default
             */
            purpose: string;
            /** Rows */
            rows?: number | null;
            /**
             * Suppressed Cells
             * @default 0
             */
            suppressed_cells: number;
            /**
             * Truncated
             * @default false
             */
            truncated: boolean;
        };
        /**
         * DebugTracePayload
         * @description One turn's decision breakdown, projected from its trace record.
         */
        DebugTracePayload: {
            /** Calculation Operators */
            calculation_operators?: {
                [key: string]: unknown;
            }[];
            /** Clarification Reason */
            clarification_reason?: string | null;
            /** Classification Confidence */
            classification_confidence?: number | null;
            /**
             * Epoch
             * @default 0
             */
            epoch: number;
            /** Finding Grades */
            finding_grades?: {
                [key: string]: string;
            };
            /** Grades */
            grades?: {
                [key: string]: string;
            };
            interpretation?: components["schemas"]["DebugInterpretation"] | null;
            /** Investigation Id */
            investigation_id: string;
            /** Llm Calls */
            llm_calls?: components["schemas"]["DebugLlmCall"][];
            /**
             * Pack Id
             * @default
             */
            pack_id: string;
            /**
             * Pack Snapshot Id
             * @default
             */
            pack_snapshot_id: string;
            /**
             * Pack Version
             * @default
             */
            pack_version: string;
            /** Plan Hash */
            plan_hash?: string | null;
            /** Playbook Id */
            playbook_id?: string | null;
            /** Probes */
            probes?: components["schemas"]["DebugProbe"][];
            /** Question */
            question?: string | null;
            /**
             * Re Anchored
             * @default false
             */
            re_anchored: boolean;
            /** Reconciliation */
            reconciliation?: string | null;
            /** Redactions */
            redactions?: string[];
            /** Referent Resolutions */
            referent_resolutions?: {
                [key: string]: unknown;
            }[];
            /** Refinement Operators */
            refinement_operators?: {
                [key: string]: unknown;
            }[];
            /** Refinement Rationale */
            refinement_rationale?: string | null;
            /** Session Id */
            session_id: string;
            settings?: components["schemas"]["SessionSettingsModel"];
            /** Template Hashes */
            template_hashes?: {
                [key: string]: string;
            };
            /** Timings Ms */
            timings_ms?: {
                [key: string]: number;
            };
            /** Trace Id */
            trace_id: string;
            /** Turn Class */
            turn_class?: string | null;
            /** Turn Id */
            turn_id: string;
            /** Warnings */
            warnings?: string[];
            /**
             * Watermark Id
             * @default
             */
            watermark_id: string;
            /**
             * Watermark Stale
             * @default false
             */
            watermark_stale: boolean;
            /** Weakest Grade */
            weakest_grade?: string | null;
        };
        /** DefinitionalPayload */
        DefinitionalPayload: {
            /** Pack Id */
            pack_id: string;
            /** Pack Snapshot Id */
            pack_snapshot_id: string;
            /** Pack Version */
            pack_version: string;
            /** Question */
            question: string;
            /** Terms */
            terms?: components["schemas"]["TermPayload"][];
        };
        /** DrillIntoModel */
        DrillIntoModel: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            op: "drill_into";
            /** Target */
            target: string;
        };
        /** ErrorEnvelope */
        ErrorEnvelope: {
            /** Code */
            code: string;
            /** Correlation Id */
            correlation_id: string;
            /** Message */
            message: string;
        };
        /**
         * EvidenceDepth
         * @description How wide the platform's own top-N cutoffs are planned.
         * @enum {string}
         */
        EvidenceDepth: "standard" | "deep";
        /**
         * EvidenceMetricRef
         * @description A metric a probe read, with the contract version it was read under.
         *
         *     Both halves come off the executed frame's schema — the version the
         *     connector stamped on the column, not the version the plan asked for,
         *     because those differ exactly when a pack promotion lands mid-session
         *     and that is the case worth seeing.
         */
        EvidenceMetricRef: {
            /** Contract Version */
            contract_version?: number | null;
            /** Id */
            id: string;
        };
        /**
         * EvidencePayload
         * @description Everything an answer can honestly say about its own working.
         */
        EvidencePayload: {
            /** Answer Grade */
            answer_grade?: string | null;
            /**
             * Cache Hits
             * @default 0
             */
            cache_hits: number;
            /** Probes */
            probes?: components["schemas"]["EvidenceProbePayload"][];
            reconciliation?: components["schemas"]["EvidenceReconciliation"] | null;
            /**
             * Warehouse Queries
             * @default 0
             */
            warehouse_queries: number;
            /**
             * Zero Probe Turn
             * @default true
             */
            zero_probe_turn: boolean;
        };
        /**
         * EvidenceProbePayload
         * @description One data check: what it was for, and what came back.
         *
         *     ``rows`` is ``None`` for a probe that was planned but never executed
         *     (a turn that stopped at clarification, a pruned node) — distinct from
         *     ``0``, which means the warehouse was asked and answered "nothing".
         */
        EvidenceProbePayload: {
            /**
             * Cache Hit
             * @default false
             */
            cache_hit: boolean;
            /**
             * Duration Ms
             * @default 0
             */
            duration_ms: number;
            /** Grade */
            grade?: string | null;
            /** Hash */
            hash: string;
            /** Id */
            id: string;
            /**
             * Kind
             * @default
             */
            kind: string;
            /** Limit */
            limit?: number | null;
            /** Metrics */
            metrics?: components["schemas"]["EvidenceMetricRef"][];
            /**
             * Purpose
             * @default
             */
            purpose: string;
            /** Rows */
            rows?: number | null;
            /**
             * Suppressed Cells
             * @default 0
             */
            suppressed_cells: number;
            /**
             * Truncated
             * @default false
             */
            truncated: boolean;
        };
        /**
         * EvidenceReconciliation
         * @description The §7.8 verdict this turn recorded, split for display.
         *
         *     ``summary`` is the recorded string verbatim (``status=<verdict>`` with
         *     optional ``; reason=...`` / ``; failed measures: ...``); ``status`` and
         *     ``detail`` are that same string parsed, never a second judgement.
         */
        EvidenceReconciliation: {
            /** Detail */
            detail?: string | null;
            /** Status */
            status: string;
            /** Summary */
            summary: string;
        };
        /** ExpandModel */
        ExpandModel: {
            /** Limit */
            limit: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            op: "expand";
        };
        /** ExplainModel */
        ExplainModel: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            op: "explain";
            /** Target */
            target: string;
        };
        /** FilterChip */
        FilterChip: {
            /** Dimension */
            dimension: string;
            /** Op */
            op: string;
            /** Origin Turn */
            origin_turn?: string | null;
            /**
             * Pinned
             * @default false
             */
            pinned: boolean;
            /** Values */
            values: string[];
        };
        /** FindingPayload */
        FindingPayload: {
            /** Benchmarks */
            benchmarks?: components["schemas"]["BenchmarkPayload"][];
            /**
             * Confidence
             * @default high
             */
            confidence: string;
            /**
             * Grade
             * @default direct
             */
            grade: string;
            /** Impact Cents */
            impact_cents?: number | null;
            /** Metric Ids */
            metric_ids?: string[];
            /** Referent */
            referent: string;
            /** Statement */
            statement: string;
            /** Suggested Refinements */
            suggested_refinements?: string[];
            /** Title */
            title: string;
            /** Values */
            values?: components["schemas"]["FindingValue"][];
        };
        /** FindingValue */
        FindingValue: {
            /** Name */
            name: string;
            /** Value */
            value?: string | number | boolean | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** InvestigationResponse */
        InvestigationResponse: {
            /** Chart Specs */
            chart_specs?: components["schemas"]["ChartSpec"][];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            evidence?: components["schemas"]["EvidencePayload"] | null;
            /** Findings */
            findings?: components["schemas"]["FindingPayload"][];
            /** Investigation Id */
            investigation_id: string;
            metric?: components["schemas"]["MetricProvenancePayload"] | null;
            /** Parent Id */
            parent_id?: string | null;
            /** Plan Hash */
            plan_hash?: string | null;
            /** Question */
            question?: string | null;
            /** Session Id */
            session_id: string;
            /** Status */
            status: string;
            /** Turn Class */
            turn_class: string;
            /** Turn Id */
            turn_id: string;
            /** Warnings */
            warnings?: string[];
        };
        /** LineageEdgePayload */
        LineageEdgePayload: {
            /** Child Id */
            child_id: string;
            /** Operators */
            operators?: {
                [key: string]: unknown;
            }[];
            /** Parent Id */
            parent_id: string;
            /** Turn Id */
            turn_id: string;
        };
        /** MetaAnswerPayload */
        MetaAnswerPayload: {
            /** Finding Values */
            finding_values?: components["schemas"]["FindingValue"][];
            /** Grades */
            grades?: {
                [key: string]: string;
            };
            /** Investigation Id */
            investigation_id: string;
            /** Label */
            label: string;
            /** Operators */
            operators?: {
                [key: string]: unknown;
            }[];
            /** Probes */
            probes?: {
                [key: string]: unknown;
            }[];
            /** Reconciliation */
            reconciliation?: string | null;
            /** Referent */
            referent: string;
            /** Warnings */
            warnings?: string[];
        };
        /**
         * MetricProvenancePayload
         * @description The governed provenance of one answer's numbers.
         *
         *     ``metrics`` is the honest whole: every governed metric this turn's
         *     probes named, in recorded order, each with the contract version the
         *     connector stamped when it ran (``None`` when the probe was planned and
         *     never executed). A playbook turn legitimately has several, and this
         *     payload says so rather than electing one of them the headline.
         *
         *     ``primary`` is set only when ONE governed contract stands behind the
         *     answer — either the interpretation named it as governing (the engine's
         *     own ``governing[0]``), or exactly one metric was read all turn. On a
         *     playbook turn that ran several, it is ``None``: there is no single
         *     contract to point at, and inventing one would be the exact overclaim
         *     the badge exists to prevent.
         *
         *     An empty ``metrics`` with no ``primary`` is a turn that measured
         *     nothing governed — a definitional answer, a META citation. The pack
         *     fields still travel: which pack was pinned is a fact about the turn
         *     even when the turn read no metric.
         */
        MetricProvenancePayload: {
            /** Metrics */
            metrics?: components["schemas"]["EvidenceMetricRef"][];
            /**
             * Pack Id
             * @default
             */
            pack_id: string;
            /**
             * Pack Snapshot Id
             * @default
             */
            pack_snapshot_id: string;
            /**
             * Pack Version
             * @default
             */
            pack_version: string;
            /** Playbook Id */
            playbook_id?: string | null;
            primary?: components["schemas"]["EvidenceMetricRef"] | null;
        };
        /**
         * NarrativeDepth
         * @description How much the narrative composer is asked to write.
         * @enum {string}
         */
        NarrativeDepth: "summary" | "analyst";
        /**
         * OpenSessionRequest
         * @description Open (or re-join) a session.
         *
         *     ``tenant`` is **advisory**. It used to be the only thing deciding which
         *     tenant a session belonged to, and nothing verified it; the tenant now
         *     comes from the caller's signed credential and this field is only
         *     cross-checked against it, so naming a different tenant is refused
         *     rather than honored. Leave it empty and the credential decides.
         */
        OpenSessionRequest: {
            /** Session Id */
            session_id?: string | null;
            settings?: components["schemas"]["SessionSettingsModel"] | null;
            /**
             * Tenant
             * @default
             */
            tenant: string;
        };
        /** PivotModel */
        PivotModel: {
            /** Measures */
            measures: string[];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            op: "pivot";
        };
        /**
         * PortfolioResponse
         * @description Detected anomalies at the pinned watermark, governed-priority ranked.
         */
        PortfolioResponse: {
            /**
             * Formula Version
             * @default
             */
            formula_version: string;
            /** Items */
            items?: components["schemas"]["AnomalyCard"][];
            /**
             * Status
             * @default empty
             * @enum {string}
             */
            status: "ok" | "empty";
            /**
             * Tenant
             * @default
             */
            tenant: string;
            /** Warnings */
            warnings?: string[];
            /**
             * Watermark Id
             * @default
             */
            watermark_id: string;
            /** Weights */
            weights?: {
                [key: string]: number;
            };
        };
        /** RankByModel */
        RankByModel: {
            /** By */
            by: string;
            /**
             * Descending
             * @default true
             */
            descending: boolean;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            op: "rank_by";
        };
        /** ReferentPayload */
        ReferentPayload: {
            /** Id */
            id: string;
            /** Kind */
            kind: string;
            /** Label */
            label: string;
        };
        /** RemoveFilterModel */
        RemoveFilterModel: {
            /** Dimension */
            dimension: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            op: "remove_filter";
        };
        /** ResetContextModel */
        ResetContextModel: {
            /**
             * Keep Pins
             * @default true
             */
            keep_pins: boolean;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            op: "reset_context";
        };
        /** SessionLineageResponse */
        SessionLineageResponse: {
            /** Edges */
            edges?: components["schemas"]["LineageEdgePayload"][];
            /** Investigations */
            investigations?: components["schemas"]["InvestigationResponse"][];
            session: components["schemas"]["SessionResponse"];
        };
        /**
         * SessionListResponse
         * @description The caller tenant's sessions, newest activity first.
         *
         *     ``total`` counts every session the tenant owns, so a page truncated by
         *     ``limit`` cannot be mistaken for the whole history. ``tenant`` names
         *     whose list this is — the same reason :class:`PortfolioResponse` carries
         *     it: "whose worklist is this?" must be answerable from the payload.
         */
        SessionListResponse: {
            /**
             * Limit
             * @default 0
             */
            limit: number;
            /** Sessions */
            sessions?: components["schemas"]["SessionSummary"][];
            /**
             * Tenant
             * @default
             */
            tenant: string;
            /**
             * Total
             * @default 0
             */
            total: number;
        };
        /** SessionResponse */
        SessionResponse: {
            /** Epoch */
            epoch: number;
            /**
             * Newest Data Date
             * Format: date
             */
            newest_data_date: string;
            /** Pack Id */
            pack_id: string;
            /** Pack Version */
            pack_version: string;
            /** Session Id */
            session_id: string;
            settings?: components["schemas"]["SessionSettingsModel"];
            /** Tenant */
            tenant: string;
            /** Watermark Id */
            watermark_id: string;
            /**
             * Watermark Loaded At
             * Format: date-time
             */
            watermark_loaded_at: string;
        };
        /**
         * SessionSettingsModel
         * @description The settings a caller applies to a session (or to one turn).
         */
        SessionSettingsModel: {
            /**
             * Debug
             * @default false
             */
            debug: boolean;
            /** @default standard */
            evidence_depth: components["schemas"]["EvidenceDepth"];
            /** Max Turn Cost Usd */
            max_turn_cost_usd?: string | null;
            /** Model Tier */
            model_tier?: string | null;
            /** @default summary */
            narrative_depth: components["schemas"]["NarrativeDepth"];
        };
        /**
         * SessionSummary
         * @description One row of ``GET /v1/sessions`` — enough to pick a session, and
         *     nothing more.
         *
         *     ``title`` is the session's FIRST question, verbatim, or ``"New
         *     session"`` when nothing has been asked yet: a session record carries no
         *     name, and a generated one would be a label the analyst never wrote.
         *     ``last_activity`` is derived from the session's newest investigation
         *     (its own ``created_at`` when it has none), so the ordering an analyst
         *     sees is when a session was last *worked*, not when it was opened.
         *
         *     Deliberately not a :class:`SessionResponse`: a list row must not imply
         *     a pinned watermark or an epoch, both of which are facts about a session
         *     you have actually joined.
         */
        SessionSummary: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Last Activity
             * Format: date-time
             */
            last_activity: string;
            /** Session Id */
            session_id: string;
            /** Title */
            title: string;
            /** Turn Count */
            turn_count: number;
        };
        /** SetComparisonModel */
        SetComparisonModel: {
            custom?: components["schemas"]["AbsoluteWindowModel"] | null;
            /** Kind */
            kind?: ("prior_period" | "prior_year") | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            op: "set_comparison";
        };
        /** SetDimensionsModel */
        SetDimensionsModel: {
            /** Dimensions */
            dimensions: string[];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            op: "set_dimensions";
        };
        /** SetGrainModel */
        SetGrainModel: {
            /**
             * Entity
             * @enum {string}
             */
            entity: "claim" | "line" | "encounter" | "transaction" | "remit" | "denial";
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            op: "set_grain";
            /** Time Bucket */
            time_bucket?: ("day" | "week" | "month") | null;
        };
        /** SetWindowModel */
        SetWindowModel: {
            /** Basis */
            basis?: string | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            op: "set_window";
            /** Window */
            window: components["schemas"]["WindowSpecModel"] | components["schemas"]["AbsoluteWindowModel"];
        };
        /**
         * SettingsBoundsPayload
         * @description What a deployment will accept — published so a UI can render the
         *     controls honestly instead of guessing and discovering refusals.
         */
        SettingsBoundsPayload: {
            /**
             * Debug Available
             * @default false
             */
            debug_available: boolean;
            /**
             * Default Model Tier
             * @default
             */
            default_model_tier: string;
            /**
             * Evidence Depth Deep Multiplier
             * @default 1
             */
            evidence_depth_deep_multiplier: number;
            /** Evidence Depths */
            evidence_depths?: string[];
            /**
             * Max Turn Cost Usd
             * @default 0
             */
            max_turn_cost_usd: string;
            /**
             * Model Tier Effective
             * @default false
             */
            model_tier_effective: boolean;
            /** Model Tiers */
            model_tiers?: string[];
            /** Narrative Depths */
            narrative_depths?: string[];
        };
        /** TermPayload */
        TermPayload: {
            /** Definition */
            definition: string;
            /** Kind */
            kind: string;
            /** Source */
            source?: string | null;
            /** Term */
            term: string;
            /** Title */
            title: string;
        };
        /** TurnAnswer */
        TurnAnswer: {
            /** Benchmarks */
            benchmarks?: components["schemas"]["BenchmarkPayload"][];
            /** Chart Specs */
            chart_specs?: components["schemas"]["ChartSpec"][];
            context_header?: components["schemas"]["ContextHeaderPayload"] | null;
            debug?: components["schemas"]["DebugTracePayload"] | null;
            definitional?: components["schemas"]["DefinitionalPayload"] | null;
            evidence?: components["schemas"]["EvidencePayload"];
            /** Findings */
            findings?: components["schemas"]["FindingPayload"][];
            /** Investigation Id */
            investigation_id: string;
            meta_answer?: components["schemas"]["MetaAnswerPayload"] | null;
            metric?: components["schemas"]["MetricProvenancePayload"] | null;
            /** Narrative */
            narrative?: string | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            outcome: "answer";
            /** Plan Hash */
            plan_hash?: string | null;
            /** Reconciliation */
            reconciliation?: string | null;
            /** Referents */
            referents?: components["schemas"]["ReferentPayload"][];
            /** Session Id */
            session_id: string;
            /** Turn Class */
            turn_class: string;
            usage?: components["schemas"]["UsageSummary"];
            /** Warnings */
            warnings?: string[];
            /**
             * Watermark Stale
             * @default false
             */
            watermark_stale: boolean;
        };
        /** TurnClarification */
        TurnClarification: {
            debug?: components["schemas"]["DebugTracePayload"] | null;
            /** Investigation Id */
            investigation_id: string;
            /** Options */
            options?: string[];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            outcome: "clarification_required";
            /** Question */
            question: string;
            /** Reason */
            reason?: string | null;
            /** Session Id */
            session_id: string;
            usage?: components["schemas"]["UsageSummary"];
            /**
             * Watermark Stale
             * @default false
             */
            watermark_stale: boolean;
        };
        /** TurnError */
        TurnError: {
            error: components["schemas"]["ErrorEnvelope"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            outcome: "error";
            /** Session Id */
            session_id?: string | null;
        };
        /**
         * TurnRequest
         * @description One turn: an utterance, a typed investigation spec, OR typed
         *     refinement operators (§12).
         */
        TurnRequest: {
            /** Clarification Response */
            clarification_response?: string | null;
            /** Correlation Id */
            correlation_id?: string | null;
            /** Idempotency Key */
            idempotency_key?: string | null;
            /**
             * Re Anchor
             * @default false
             */
            re_anchor: boolean;
            /** Refinements */
            refinements?: (components["schemas"]["SetDimensionsModel"] | components["schemas"]["AddFilterModel"] | components["schemas"]["RemoveFilterModel"] | components["schemas"]["SetWindowModel"] | components["schemas"]["SetComparisonModel"] | components["schemas"]["SetGrainModel"] | components["schemas"]["DrillIntoModel"] | components["schemas"]["PivotModel"] | components["schemas"]["ExplainModel"] | components["schemas"]["RankByModel"] | components["schemas"]["ExpandModel"] | components["schemas"]["ResetContextModel"])[] | null;
            settings?: components["schemas"]["SessionSettingsModel"] | null;
            spec?: components["schemas"]["TypedInvestigationSpec"] | null;
            /** Utterance */
            utterance?: string | null;
        };
        /**
         * TurnStreamEvent
         * @description One Server-Sent Event frame on the turn route.
         *
         *     On the wire each frame is ``event: <kind>\ndata: <json>\n\n``; this
         *     model documents that pairing (it is never serialized as a JSON body).
         *     Ordering: ``stage*`` interleaved with ``warning*``, then either
         *     ``clarification`` or (``context_header``, ``finding*``, ``chart_spec*``,
         *     ``narrative_delta*``), always terminated by exactly one
         *     ``turn_complete`` — or by ``error`` if the turn failed.
         */
        TurnStreamEvent: {
            /** Data */
            data: {
                [key: string]: unknown;
            };
            /**
             * Event
             * @enum {string}
             */
            event: "stage" | "warning" | "clarification" | "context_header" | "finding" | "chart_spec" | "narrative_delta" | "error" | "turn_complete";
        };
        /**
         * TypedInvestigationSpec
         * @description An explicit, typed investigation — the typed twin of interpretation.
         *
         *     A turn carrying one of these is a NEW_INVESTIGATION *by construction*:
         *     it names its own governed metrics, dimensions, scope and window, so
         *     there is nothing to infer and no parent investigation to refine. The
         *     engine builds the ``AnalysisSpec`` from it directly with **zero model
         *     calls**; the §6.6 validation pass then runs unchanged, so a typed spec
         *     earns exactly the same grades, warnings and refusals an interpreted
         *     one does. It skips the guessing, never the governance.
         *
         *     This is the anchor a typed *refinement* has always needed and never
         *     had. A refinement edits a parent investigation; a portfolio card, a
         *     chart click in a fresh session, a saved view or a scheduled brief has
         *     no parent — it has an intent that is already typed. Expressing that as
         *     a first turn (rather than minting a hidden portfolio-anchored session
         *     per surface) keeps one investigation pipeline: whatever posts this
         *     gets the same planning, validation, grading, findings and trace as a
         *     sentence would.
         */
        TypedInvestigationSpec: {
            /** Basis */
            basis?: string | null;
            /** Comparison */
            comparison?: ("prior_period" | "prior_year") | null;
            /** Dimensions */
            dimensions?: string[];
            /** Filters */
            filters?: components["schemas"]["AddFilterModel"][];
            /** Metric Ids */
            metric_ids: string[];
            /** Window */
            window: components["schemas"]["WindowSpecModel"] | components["schemas"]["AbsoluteWindowModel"];
        };
        /**
         * UsageSummary
         * @description What this turn spent on the model.
         *
         *     ``input_tokens`` is EVERY prompt token the turn read — the uncached
         *     remainder plus what was written to and served from the provider's
         *     prompt cache. The provider reports those three separately and names
         *     only the first ``input_tokens``; publishing that one field made turns
         *     read ``input_tokens: 4`` against ``output_tokens: 953``. The cached
         *     split rides on the two fields below rather than being lost, so a reader
         *     can still tell a cheap cached prompt from an expensive cold one.
         */
        UsageSummary: {
            /**
             * Cache Creation Tokens
             * @default 0
             */
            cache_creation_tokens: number;
            /**
             * Cache Read Tokens
             * @default 0
             */
            cache_read_tokens: number;
            /**
             * Cost Usd
             * @default 0
             */
            cost_usd: string;
            /**
             * Input Tokens
             * @default 0
             */
            input_tokens: number;
            /**
             * Llm Calls
             * @default 0
             */
            llm_calls: number;
            /**
             * Output Tokens
             * @default 0
             */
            output_tokens: number;
            /**
             * Schema Retries
             * @default 0
             */
            schema_retries: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * WindowSpecModel
         * @description A relative window; ``quantity`` is a decimal string ("1", "3.25").
         */
        WindowSpecModel: {
            /**
             * Mode
             * @enum {string}
             */
            mode: "trailing" | "full_periods" | "to_date";
            /** Quantity */
            quantity: string;
            /**
             * Unit
             * @enum {string}
             */
            unit: "day" | "week" | "month" | "quarter" | "year";
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_capabilities_v1_capabilities_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CapabilitiesResponse"];
                };
            };
            /** @description Stable §12 error code: the request was understood but could not be answered (BINDING_AMBIGUOUS, UNSUPPORTED_CONCEPT, INSUFFICIENT_EVIDENCE, GRAIN_INCOMPATIBLE, POLICY_DENIED, …). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Missing, malformed, or expired bearer token (POLICY_DENIED). The token carries the tenant; it is never taken from the request body. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description A valid credential for a different tenant (POLICY_DENIED). Session and investigation ids are not secrets, so a cross-tenant read is refused rather than disguised as a 404. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unknown session, investigation, or referent (REFERENT_NOT_FOUND). */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description WATERMARK_STALE or CONTEXT_CONFLICT — the pinned context cannot absorb the request without an explicit decision. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description SOURCE_UNAVAILABLE or DATA_LOADING — the analytical source cannot serve this watermark right now. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    health_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Stable §12 error code: the request was understood but could not be answered (BINDING_AMBIGUOUS, UNSUPPORTED_CONCEPT, INSUFFICIENT_EVIDENCE, GRAIN_INCOMPATIBLE, POLICY_DENIED, …). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Missing, malformed, or expired bearer token (POLICY_DENIED). The token carries the tenant; it is never taken from the request body. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description A valid credential for a different tenant (POLICY_DENIED). Session and investigation ids are not secrets, so a cross-tenant read is refused rather than disguised as a 404. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unknown session, investigation, or referent (REFERENT_NOT_FOUND). */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description WATERMARK_STALE or CONTEXT_CONFLICT — the pinned context cannot absorb the request without an explicit decision. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description SOURCE_UNAVAILABLE or DATA_LOADING — the analytical source cannot serve this watermark right now. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    get_investigation_v1_investigations__investigation_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                investigation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvestigationResponse"];
                };
            };
            /** @description Stable §12 error code: the request was understood but could not be answered (BINDING_AMBIGUOUS, UNSUPPORTED_CONCEPT, INSUFFICIENT_EVIDENCE, GRAIN_INCOMPATIBLE, POLICY_DENIED, …). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Missing, malformed, or expired bearer token (POLICY_DENIED). The token carries the tenant; it is never taken from the request body. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description A valid credential for a different tenant (POLICY_DENIED). Session and investigation ids are not secrets, so a cross-tenant read is refused rather than disguised as a 404. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unknown session, investigation, or referent (REFERENT_NOT_FOUND). */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description WATERMARK_STALE or CONTEXT_CONFLICT — the pinned context cannot absorb the request without an explicit decision. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description SOURCE_UNAVAILABLE or DATA_LOADING — the analytical source cannot serve this watermark right now. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    get_trace_v1_investigations__investigation_id__trace_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                investigation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DebugTracePayload"];
                };
            };
            /** @description Stable §12 error code: the request was understood but could not be answered (BINDING_AMBIGUOUS, UNSUPPORTED_CONCEPT, INSUFFICIENT_EVIDENCE, GRAIN_INCOMPATIBLE, POLICY_DENIED, …). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Missing, malformed, or expired bearer token (POLICY_DENIED). The token carries the tenant; it is never taken from the request body. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description A valid credential for a different tenant (POLICY_DENIED). Session and investigation ids are not secrets, so a cross-tenant read is refused rather than disguised as a 404. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unknown session, investigation, or referent (REFERENT_NOT_FOUND). */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description WATERMARK_STALE or CONTEXT_CONFLICT — the pinned context cannot absorb the request without an explicit decision. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description SOURCE_UNAVAILABLE or DATA_LOADING — the analytical source cannot serve this watermark right now. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    get_portfolio_v1_portfolio_latest_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioResponse"];
                };
            };
            /** @description Stable §12 error code: the request was understood but could not be answered (BINDING_AMBIGUOUS, UNSUPPORTED_CONCEPT, INSUFFICIENT_EVIDENCE, GRAIN_INCOMPATIBLE, POLICY_DENIED, …). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Missing, malformed, or expired bearer token (POLICY_DENIED). The token carries the tenant; it is never taken from the request body. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description A valid credential for a different tenant (POLICY_DENIED). Session and investigation ids are not secrets, so a cross-tenant read is refused rather than disguised as a 404. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unknown session, investigation, or referent (REFERENT_NOT_FOUND). */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description WATERMARK_STALE or CONTEXT_CONFLICT — the pinned context cannot absorb the request without an explicit decision. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description SOURCE_UNAVAILABLE or DATA_LOADING — the analytical source cannot serve this watermark right now. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    list_sessions_v1_sessions_get: {
        parameters: {
            query?: {
                /** @description Page size, newest activity first. */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionListResponse"];
                };
            };
            /** @description Stable §12 error code: the request was understood but could not be answered (BINDING_AMBIGUOUS, UNSUPPORTED_CONCEPT, INSUFFICIENT_EVIDENCE, GRAIN_INCOMPATIBLE, POLICY_DENIED, …). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Missing, malformed, or expired bearer token (POLICY_DENIED). The token carries the tenant; it is never taken from the request body. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description A valid credential for a different tenant (POLICY_DENIED). Session and investigation ids are not secrets, so a cross-tenant read is refused rather than disguised as a 404. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unknown session, investigation, or referent (REFERENT_NOT_FOUND). */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description WATERMARK_STALE or CONTEXT_CONFLICT — the pinned context cannot absorb the request without an explicit decision. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description SOURCE_UNAVAILABLE or DATA_LOADING — the analytical source cannot serve this watermark right now. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    open_session_v1_sessions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OpenSessionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
            /** @description Stable §12 error code: the request was understood but could not be answered (BINDING_AMBIGUOUS, UNSUPPORTED_CONCEPT, INSUFFICIENT_EVIDENCE, GRAIN_INCOMPATIBLE, POLICY_DENIED, …). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Missing, malformed, or expired bearer token (POLICY_DENIED). The token carries the tenant; it is never taken from the request body. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description A valid credential for a different tenant (POLICY_DENIED). Session and investigation ids are not secrets, so a cross-tenant read is refused rather than disguised as a 404. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unknown session, investigation, or referent (REFERENT_NOT_FOUND). */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description WATERMARK_STALE or CONTEXT_CONFLICT — the pinned context cannot absorb the request without an explicit decision. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description SOURCE_UNAVAILABLE or DATA_LOADING — the analytical source cannot serve this watermark right now. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    get_lineage_v1_sessions__session_id__lineage_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionLineageResponse"];
                };
            };
            /** @description Stable §12 error code: the request was understood but could not be answered (BINDING_AMBIGUOUS, UNSUPPORTED_CONCEPT, INSUFFICIENT_EVIDENCE, GRAIN_INCOMPATIBLE, POLICY_DENIED, …). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Missing, malformed, or expired bearer token (POLICY_DENIED). The token carries the tenant; it is never taken from the request body. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description A valid credential for a different tenant (POLICY_DENIED). Session and investigation ids are not secrets, so a cross-tenant read is refused rather than disguised as a 404. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unknown session, investigation, or referent (REFERENT_NOT_FOUND). */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description WATERMARK_STALE or CONTEXT_CONFLICT — the pinned context cannot absorb the request without an explicit decision. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description SOURCE_UNAVAILABLE or DATA_LOADING — the analytical source cannot serve this watermark right now. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    submit_turn_v1_sessions__session_id__turns_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TurnRequest"];
            };
        };
        responses: {
            /** @description The turn's `TurnResponse` (JSON), or — with `Accept: text/event-stream` — the SSE stream whose frames are `TurnStreamEvent`. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TurnAnswer"] | components["schemas"]["TurnClarification"] | components["schemas"]["TurnError"];
                    "text/event-stream": components["schemas"]["TurnStreamEvent"];
                };
            };
            /** @description Stable §12 error code: the request was understood but could not be answered (BINDING_AMBIGUOUS, UNSUPPORTED_CONCEPT, INSUFFICIENT_EVIDENCE, GRAIN_INCOMPATIBLE, POLICY_DENIED, …). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Missing, malformed, or expired bearer token (POLICY_DENIED). The token carries the tenant; it is never taken from the request body. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description A valid credential for a different tenant (POLICY_DENIED). Session and investigation ids are not secrets, so a cross-tenant read is refused rather than disguised as a 404. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unknown session, investigation, or referent (REFERENT_NOT_FOUND). */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description WATERMARK_STALE or CONTEXT_CONFLICT — the pinned context cannot absorb the request without an explicit decision. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description SOURCE_UNAVAILABLE or DATA_LOADING — the analytical source cannot serve this watermark right now. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
}
